#!/bin/bash
touch src/core/functions/acos.rs
touch src/core/functions/acosf.rs
touch src/core/functions/acosh.rs
touch src/core/functions/acoshf.rs
touch src/core/functions/asin.rs
touch src/core/functions/asinf.rs
touch src/core/functions/asinh.rs
touch src/core/functions/asinhf.rs
touch src/core/functions/atan.rs
touch src/core/functions/atan2.rs
touch src/core/functions/atan2f.rs
touch src/core/functions/atanf.rs
touch src/core/functions/atanh.rs
touch src/core/functions/atanhf.rs
touch src/core/functions/cbrt.rs
touch src/core/functions/cbrtf.rs
touch src/core/functions/ceil.rs
touch src/core/functions/ceilf.rs
touch src/core/functions/copysign.rs
touch src/core/functions/copysignf.rs
touch src/core/functions/cos.rs
touch src/core/functions/cosf.rs
touch src/core/functions/cosh.rs
touch src/core/functions/coshf.rs
touch src/core/functions/erf.rs
touch src/core/functions/erfc.rs
touch src/core/functions/erfcf.rs
touch src/core/functions/erff.rs
touch src/core/functions/exp.rs
touch src/core/functions/exp2.rs
touch src/core/functions/exp2f.rs
touch src/core/functions/exp10.rs
touch src/core/functions/exp10f.rs
touch src/core/functions/expf.rs
touch src/core/functions/expm1.rs
touch src/core/functions/expm1f.rs
touch src/core/functions/fabs.rs
touch src/core/functions/fabsf.rs
touch src/core/functions/fdim.rs
touch src/core/functions/fdimf.rs
touch src/core/functions/floor.rs
touch src/core/functions/floorf.rs
touch src/core/functions/fma.rs
touch src/core/functions/fmaf.rs
touch src/core/functions/fmax.rs
touch src/core/functions/fmaxf.rs
touch src/core/functions/fmaximum.rs
touch src/core/functions/fmaximum_num.rs
touch src/core/functions/fmaximum_numf.rs
touch src/core/functions/fmaximumf.rs
touch src/core/functions/fmin.rs
touch src/core/functions/fminf.rs
touch src/core/functions/fminimum.rs
touch src/core/functions/fminimum_num.rs
touch src/core/functions/fminimum_numf.rs
touch src/core/functions/fminimumf.rs
touch src/core/functions/fmod.rs
touch src/core/functions/fmodf.rs
touch src/core/functions/frexp.rs
touch src/core/functions/frexpf.rs
touch src/core/functions/hypot.rs
touch src/core/functions/hypotf.rs
touch src/core/functions/ilogb.rs
touch src/core/functions/ilogbf.rs
touch src/core/functions/j0.rs
touch src/core/functions/j0f.rs
touch src/core/functions/j1.rs
touch src/core/functions/j1f.rs
touch src/core/functions/jn.rs
touch src/core/functions/jnf.rs
touch src/core/functions/ldexp.rs
touch src/core/functions/ldexpf.rs
touch src/core/functions/lgamma.rs
touch src/core/functions/lgamma_r.rs
touch src/core/functions/lgammaf.rs
touch src/core/functions/lgammaf_r.rs
touch src/core/functions/log.rs
touch src/core/functions/log2.rs
touch src/core/functions/log1p.rs
touch src/core/functions/log1pf.rs
touch src/core/functions/log2f.rs
touch src/core/functions/log10.rs
touch src/core/functions/log10f.rs
touch src/core/functions/logf.rs
touch src/core/functions/modf.rs
touch src/core/functions/modff.rs
touch src/core/functions/nextafter.rs
touch src/core/functions/nextafterf.rs
touch src/core/functions/pow.rs
touch src/core/functions/powf.rs
touch src/core/functions/remainder.rs
touch src/core/functions/remainderf.rs
touch src/core/functions/remquo.rs
touch src/core/functions/remquof.rs
touch src/core/functions/rint.rs
touch src/core/functions/rintf.rs
touch src/core/functions/round.rs
touch src/core/functions/roundeven.rs
touch src/core/functions/roundevenf.rs
touch src/core/functions/roundf.rs
touch src/core/functions/scalbn.rs
touch src/core/functions/scalbnf.rs
touch src/core/functions/sin.rs
touch src/core/functions/sincos.rs
touch src/core/functions/sincosf.rs
touch src/core/functions/sinf.rs
touch src/core/functions/sinh.rs
touch src/core/functions/sinhf.rs
touch src/core/functions/sqrt.rs
touch src/core/functions/sqrtf.rs
touch src/core/functions/tan.rs
touch src/core/functions/tanf.rs
touch src/core/functions/tanh.rs
touch src/core/functions/tanhf.rs
touch src/core/functions/tgamma.rs
touch src/core/functions/tgammaf.rs
touch src/core/functions/trunc.rs
touch src/core/functions/truncf.rs
touch src/core/functions/y0.rs
touch src/core/functions/y0f.rs
touch src/core/functions/y1.rs
touch src/core/functions/y1f.rs
touch src/core/functions/yn.rs
touch src/core/functions/ynf.rs